### ISSUE TITLE
Unable to import normally

### ISSUE THREAD

**Issue by Randomli** [monotonee/django-forcedfields#5]
File "/Users/random_lee/venv/python2.7/JobPlatformService/lib/python2.7/site-packages/django_forcedfields.py", line 160
SyntaxError: Non-ASCII character '\xe2' in file /Users/random_lee/venv/python2.7/JobPlatformService/lib/python2.7/site-packages/django_forcedfields.py on line 161, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by monotonee** [comment]
Hi @Randomli. Thank you for submitting this issue. Your problem is caused by a "✓" character in a doc block, the code point of which is outside of the ASCII range.

You appear to be using Python 2 which, as you may have noticed on [django-forcedfields' PyPI page](https://pypi.org/project/django-forcedfields/), is neither tested nor supported. In fact, even if I were to implement PEP 263 encoding hints in django-forcedfields, your import may (and likely would) still fail due to syntax supported only by Python 3.

I currently have no plans to support Python 2 in this project. I apologize for any inconvenience.
